export type CatalogLanguage = "pt-BR" | "it-IT" | "en-US" | "es-ES";
export type CatalogMuscleGroup =
  | "aquecimento"
  | "peito"
  | "costas"
  | "ombro"
  | "bracos"
  | "pernas"
  | "abdomen";

export interface CatalogExercise {
  id: string;
  canonicalNamePt: string;
  namesByLanguage: Record<CatalogLanguage, string>;
  aliasesByLanguage: Record<CatalogLanguage, string[]>;
  muscleGroup: CatalogMuscleGroup;
  videoUrl: string;
  sourceFileName: string;
  videoProvider: "local";
  movementPattern?: string;
  equipment?: string;
  tags?: string[];
}

// Base path for exercise videos in the frontend public folder
const V = "/exercise/visuals";

export const ValidatedExerciseCatalog: CatalogExercise[] = [
  // ─── AQUECIMENTO ───────────────────────────────────────────────────────────
  {
    id: "bike_academia",
    canonicalNamePt: "Bike academia",
    namesByLanguage: {
      "pt-BR": "Bike academia",
      "it-IT": "Cyclette",
      "en-US": "Stationary bike",
      "es-ES": "Bicicleta estática",
    },
    aliasesByLanguage: {
      "pt-BR": ["bike", "bicicleta ergométrica", "bicicleta academia"],
      "it-IT": ["bici da camera", "bike", "cyclette"],
      "en-US": ["bike", "exercise bike", "spin bike"],
      "es-ES": ["bicicleta", "bici estática", "bike"],
    },
    muscleGroup: "aquecimento",
    videoUrl: `${V}/aquecimento-aerobico/bike_academia.mp4`,
    sourceFileName: "bike_academia.mp4",
    videoProvider: "local",
    movementPattern: "cardio",
    equipment: "bike",
    tags: ["aquecimento", "cardio"],
  },
  {
    id: "burpee",
    canonicalNamePt: "Burpee",
    namesByLanguage: {
      "pt-BR": "Burpee",
      "it-IT": "Burpee",
      "en-US": "Burpee",
      "es-ES": "Burpee",
    },
    aliasesByLanguage: {
      "pt-BR": ["burpee"],
      "it-IT": ["burpee"],
      "en-US": ["burpee"],
      "es-ES": ["burpee"],
    },
    muscleGroup: "aquecimento",
    videoUrl: `${V}/aquecimento-aerobico/burpee.mp4`,
    sourceFileName: "burpee.mp4",
    videoProvider: "local",
    movementPattern: "cardio",
    equipment: "bodyweight",
    tags: ["aquecimento", "cardio", "corpo-livre"],
  },
  {
    id: "caminhada_esteira_inclinada",
    canonicalNamePt: "Caminhada esteira inclinada",
    namesByLanguage: {
      "pt-BR": "Caminhada esteira inclinada",
      "it-IT": "Camminata sul tapis roulant in salita",
      "en-US": "Incline treadmill walk",
      "es-ES": "Caminata en cinta inclinada",
    },
    aliasesByLanguage: {
      "pt-BR": ["esteira inclinada", "caminhada esteira"],
      "it-IT": ["tapis roulant", "camminata inclinata"],
      "en-US": ["treadmill walk", "incline walk"],
      "es-ES": ["caminata inclinada", "cinta inclinada"],
    },
    muscleGroup: "aquecimento",
    videoUrl: `${V}/aquecimento-aerobico/caminhada_esteira_inclinada.mp4`,
    sourceFileName: "caminhada_esteira_inclinada.mp4",
    videoProvider: "local",
    movementPattern: "cardio",
    equipment: "esteira",
    tags: ["aquecimento", "cardio"],
  },
  {
    id: "corda_naval",
    canonicalNamePt: "Corda naval",
    namesByLanguage: {
      "pt-BR": "Corda naval",
      "it-IT": "Battle rope",
      "en-US": "Battle rope",
      "es-ES": "Cuerda naval",
    },
    aliasesByLanguage: {
      "pt-BR": ["battle rope", "corda"],
      "it-IT": ["battle rope", "corda"],
      "en-US": ["battle rope", "rope waves"],
      "es-ES": ["cuerda", "battle rope"],
    },
    muscleGroup: "aquecimento",
    videoUrl: `${V}/aquecimento-aerobico/corda_naval.mp4`,
    sourceFileName: "corda_naval.mp4",
    videoProvider: "local",
    movementPattern: "cardio",
    equipment: "corda",
    tags: ["aquecimento", "cardio"],
  },
  {
    id: "eliptico",
    canonicalNamePt: "Elíptico",
    namesByLanguage: {
      "pt-BR": "Elíptico",
      "it-IT": "Ellittica",
      "en-US": "Elliptical",
      "es-ES": "Elíptica",
    },
    aliasesByLanguage: {
      "pt-BR": ["eliptico", "elíptico"],
      "it-IT": ["ellittica"],
      "en-US": ["elliptical", "elliptical machine"],
      "es-ES": ["elíptica", "eliptica"],
    },
    muscleGroup: "aquecimento",
    videoUrl: `${V}/aquecimento-aerobico/eliptico.mp4`,
    sourceFileName: "eliptico.mp4",
    videoProvider: "local",
    movementPattern: "cardio",
    equipment: "eliptico",
    tags: ["aquecimento", "cardio"],
  },
  {
    id: "escada_academia",
    canonicalNamePt: "Escada academia",
    namesByLanguage: {
      "pt-BR": "Escada academia",
      "it-IT": "Stepper",
      "en-US": "Stair climber",
      "es-ES": "Escaladora",
    },
    aliasesByLanguage: {
      "pt-BR": ["escada", "stepper", "escada academia"],
      "it-IT": ["stepper", "scala"],
      "en-US": ["stair climber", "step machine"],
      "es-ES": ["escaladora", "stepper"],
    },
    muscleGroup: "aquecimento",
    videoUrl: `${V}/aquecimento-aerobico/escada_academia.mp4`,
    sourceFileName: "escada_academia.mp4",
    videoProvider: "local",
    movementPattern: "cardio",
    equipment: "escada",
    tags: ["aquecimento", "cardio"],
  },
  {
    id: "polichinelo",
    canonicalNamePt: "Polichinelo",
    namesByLanguage: {
      "pt-BR": "Polichinelo",
      "it-IT": "Jumping jack",
      "en-US": "Jumping jack",
      "es-ES": "Jumping jack",
    },
    aliasesByLanguage: {
      "pt-BR": ["polichinelo", "jumping jack"],
      "it-IT": ["jumping jack", "saltelli"],
      "en-US": ["jumping jack"],
      "es-ES": ["jumping jack"],
    },
    muscleGroup: "aquecimento",
    videoUrl: `${V}/aquecimento-aerobico/polichinelo.mp4`,
    sourceFileName: "polichinelo.mp4",
    videoProvider: "local",
    movementPattern: "cardio",
    equipment: "bodyweight",
    tags: ["aquecimento", "cardio", "corpo-livre"],
  },

  // ─── ABDÔMEN / CORE ────────────────────────────────────────────────────────
  {
    id: "abs_borboleta",
    canonicalNamePt: "Abs borboleta",
    namesByLanguage: {
      "pt-BR": "Abs borboleta",
      "it-IT": "Crunch a farfalla",
      "en-US": "Butterfly crunch",
      "es-ES": "Crunch mariposa",
    },
    aliasesByLanguage: {
      "pt-BR": ["borboleta", "crunch borboleta"],
      "it-IT": ["crunch farfalla"],
      "en-US": ["butterfly crunch"],
      "es-ES": ["crunch mariposa"],
    },
    muscleGroup: "abdomen",
    videoUrl: `${V}/abdomen-core/abs_borboleta.mp4`,
    sourceFileName: "abs_borboleta.mp4",
    videoProvider: "local",
    movementPattern: "flexao",
    equipment: "bodyweight",
    tags: ["abdomen", "core"],
  },
  {
    id: "abs_canoa",
    canonicalNamePt: "Abs canoa",
    namesByLanguage: {
      "pt-BR": "Abs canoa",
      "it-IT": "Crunch a canoa",
      "en-US": "Boat crunch",
      "es-ES": "Crunch canoa",
    },
    aliasesByLanguage: {
      "pt-BR": ["canoa", "crunch canoa"],
      "it-IT": ["crunch canoa"],
      "en-US": ["boat crunch"],
      "es-ES": ["crunch canoa"],
    },
    muscleGroup: "abdomen",
    videoUrl: `${V}/abdomen-core/abs_canoa.mp4`,
    sourceFileName: "abs_canoa.mp4",
    videoProvider: "local",
    movementPattern: "flexao",
    equipment: "bodyweight",
    tags: ["abdomen", "core"],
  },
  {
    id: "abs_infra",
    canonicalNamePt: "Abs infra",
    namesByLanguage: {
      "pt-BR": "Abs infra",
      "it-IT": "Abs inferiore",
      "en-US": "Lower abs",
      "es-ES": "Abs inferior",
    },
    aliasesByLanguage: {
      "pt-BR": ["abdominal infra", "infra"],
      "it-IT": ["abs inferiore"],
      "en-US": ["lower abs"],
      "es-ES": ["abs inferior"],
    },
    muscleGroup: "abdomen",
    videoUrl: `${V}/abdomen-core/abs_infra.mp4`,
    sourceFileName: "abs_infra.mp4",
    videoProvider: "local",
    movementPattern: "flexao",
    equipment: "bodyweight",
    tags: ["abdomen", "core", "infra"],
  },
  {
    id: "abs_infra_elevacao",
    canonicalNamePt: "Abs infra elevação",
    namesByLanguage: {
      "pt-BR": "Abs infra elevação",
      "it-IT": "Abs inferiore con elevazione",
      "en-US": "Lower abs lift",
      "es-ES": "Abs inferior con elevación",
    },
    aliasesByLanguage: {
      "pt-BR": ["elevação infra", "infra elevação"],
      "it-IT": ["abs inferiore elevazione"],
      "en-US": ["lower abs lift"],
      "es-ES": ["abs inferior elevación"],
    },
    muscleGroup: "abdomen",
    videoUrl: `${V}/abdomen-core/abs_infra_elevacao.mp4`,
    sourceFileName: "abs_infra_elevacao.mp4",
    videoProvider: "local",
    movementPattern: "flexao",
    equipment: "bodyweight",
    tags: ["abdomen", "core", "infra"],
  },
  {
    id: "abs_obliquio",
    canonicalNamePt: "Abs oblíquo",
    namesByLanguage: {
      "pt-BR": "Abs oblíquo",
      "it-IT": "Obliqui",
      "en-US": "Oblique abs",
      "es-ES": "Abs oblicuo",
    },
    aliasesByLanguage: {
      "pt-BR": ["oblíquo", "obliquo", "abdominal oblíquo"],
      "it-IT": ["obliqui", "addominali obliqui"],
      "en-US": ["oblique", "side crunch"],
      "es-ES": ["oblicuo", "abdominal oblicuo"],
    },
    muscleGroup: "abdomen",
    videoUrl: `${V}/abdomen-core/abs_obliquio.mp4`,
    sourceFileName: "abs_obliquio.mp4",
    videoProvider: "local",
    movementPattern: "rotacao",
    equipment: "bodyweight",
    tags: ["abdomen", "core", "obliquo"],
  },
  {
    id: "abs_obliquio_toque_calcanhar",
    canonicalNamePt: "Abs oblíquo toque calcanhar",
    namesByLanguage: {
      "pt-BR": "Abs oblíquo toque calcanhar",
      "it-IT": "Obliqui con tocco del tallone",
      "en-US": "Heel touch oblique",
      "es-ES": "Oblicuo toque talón",
    },
    aliasesByLanguage: {
      "pt-BR": ["toque calcanhar", "heel touch"],
      "it-IT": ["tocco tallone"],
      "en-US": ["heel touch"],
      "es-ES": ["toque talón"],
    },
    muscleGroup: "abdomen",
    videoUrl: `${V}/abdomen-core/abs_obliquioi_toque_calcanhar.mp4`,
    sourceFileName: "abs_obliquioi_toque_calcanhar.mp4",
    videoProvider: "local",
    movementPattern: "rotacao",
    equipment: "bodyweight",
    tags: ["abdomen", "core", "obliquo"],
  },
  {
    id: "abs_supra_cabo",
    canonicalNamePt: "Abs supra cabo",
    namesByLanguage: {
      "pt-BR": "Abs supra cabo",
      "it-IT": "Crunch superiore al cavo",
      "en-US": "Cable crunch",
      "es-ES": "Crunch en polea",
    },
    aliasesByLanguage: {
      "pt-BR": ["crunch cabo", "abdominal cabo"],
      "it-IT": ["crunch al cavo"],
      "en-US": ["cable crunch"],
      "es-ES": ["crunch polea"],
    },
    muscleGroup: "abdomen",
    videoUrl: `${V}/abdomen-core/abs_supra_cabo.mp4`,
    sourceFileName: "abs_supra_cabo.mp4",
    videoProvider: "local",
    movementPattern: "flexao",
    equipment: "polia",
    tags: ["abdomen", "core", "supra"],
  },
  {
    id: "abs_supra_halter",
    canonicalNamePt: "Abs supra halter",
    namesByLanguage: {
      "pt-BR": "Abs supra halter",
      "it-IT": "Crunch superiore con manubrio",
      "en-US": "Dumbbell crunch",
      "es-ES": "Crunch con mancuerna",
    },
    aliasesByLanguage: {
      "pt-BR": ["crunch halter", "abdominal halter"],
      "it-IT": ["crunch manubrio"],
      "en-US": ["dumbbell crunch"],
      "es-ES": ["crunch mancuerna"],
    },
    muscleGroup: "abdomen",
    videoUrl: `${V}/abdomen-core/abs_supra_halter.mp4`,
    sourceFileName: "abs_supra_halter.mp4",
    videoProvider: "local",
    movementPattern: "flexao",
    equipment: "halter",
    tags: ["abdomen", "core", "supra"],
  },
  {
    id: "abs_tesoura",
    canonicalNamePt: "Abs tesoura",
    namesByLanguage: {
      "pt-BR": "Abs tesoura",
      "it-IT": "Sforbiciata",
      "en-US": "Scissors abs",
      "es-ES": "Abs tijera",
    },
    aliasesByLanguage: {
      "pt-BR": ["tesoura", "scissors"],
      "it-IT": ["sforbiciata"],
      "en-US": ["scissors"],
      "es-ES": ["tijera"],
    },
    muscleGroup: "abdomen",
    videoUrl: `${V}/abdomen-core/abs_tesoura.mp4`,
    sourceFileName: "abs_tesoura.mp4",
    videoProvider: "local",
    movementPattern: "alternado",
    equipment: "bodyweight",
    tags: ["abdomen", "core", "infra"],
  },
  {
    id: "abs_tesoura_vertical",
    canonicalNamePt: "Abs tesoura vertical",
    namesByLanguage: {
      "pt-BR": "Abs tesoura vertical",
      "it-IT": "Sforbiciata verticale",
      "en-US": "Vertical scissors",
      "es-ES": "Tijera vertical",
    },
    aliasesByLanguage: {
      "pt-BR": ["tesoura vertical"],
      "it-IT": ["sforbiciata verticale"],
      "en-US": ["vertical scissors"],
      "es-ES": ["tijera vertical"],
    },
    muscleGroup: "abdomen",
    videoUrl: `${V}/abdomen-core/abs_tesoura_vertical.mp4`,
    sourceFileName: "abs_tesoura_vertical.mp4",
    videoProvider: "local",
    movementPattern: "alternado",
    equipment: "bodyweight",
    tags: ["abdomen", "core", "infra"],
  },
  {
    id: "flexao_lateral_banco_romano",
    canonicalNamePt: "Flexão lateral banco romano",
    namesByLanguage: {
      "pt-BR": "Flexão lateral banco romano",
      "it-IT": "Flessione laterale alla panca romana",
      "en-US": "Lateral flexion roman bench",
      "es-ES": "Flexión lateral banco romano",
    },
    aliasesByLanguage: {
      "pt-BR": ["banco romano lateral", "flexão lateral"],
      "it-IT": ["panca romana laterale"],
      "en-US": ["roman bench lateral flexion"],
      "es-ES": ["banco romano lateral"],
    },
    muscleGroup: "abdomen",
    videoUrl: `${V}/abdomen-core/flexao_lateral_banco_romano.mp4`,
    sourceFileName: "flexao_lateral_banco_romano.mp4",
    videoProvider: "local",
    movementPattern: "flexao-lateral",
    equipment: "banco-romano",
    tags: ["abdomen", "core", "obliquo"],
  },
  {
    id: "perdigueiro",
    canonicalNamePt: "Perdigueiro",
    namesByLanguage: {
      "pt-BR": "Perdigueiro",
      "it-IT": "Bird dog",
      "en-US": "Bird dog",
      "es-ES": "Bird dog",
    },
    aliasesByLanguage: {
      "pt-BR": ["bird dog", "perdigueiro"],
      "it-IT": ["bird dog"],
      "en-US": ["bird dog"],
      "es-ES": ["bird dog"],
    },
    muscleGroup: "abdomen",
    videoUrl: `${V}/abdomen-core/perdigueiro.mp4`,
    sourceFileName: "perdigueiro.mp4",
    videoProvider: "local",
    movementPattern: "estabilizacao",
    equipment: "bodyweight",
    tags: ["core", "lombar", "estabilizacao"],
  },
  {
    id: "prancha_isometrica",
    canonicalNamePt: "Prancha isométrica",
    namesByLanguage: {
      "pt-BR": "Prancha isométrica",
      "it-IT": "Plank isometrico",
      "en-US": "Isometric plank",
      "es-ES": "Plancha isométrica",
    },
    aliasesByLanguage: {
      "pt-BR": ["prancha", "plank", "isométrica"],
      "it-IT": ["plank", "tavola"],
      "en-US": ["plank"],
      "es-ES": ["plancha"],
    },
    muscleGroup: "abdomen",
    // note: actual filename has typo "isomentrica" — using as-is
    videoUrl: `${V}/abdomen-core/prancha_isomentrica.mp4`,
    sourceFileName: "prancha_isomentrica.mp4",
    videoProvider: "local",
    movementPattern: "isometrico",
    equipment: "bodyweight",
    tags: ["core", "estabilizacao"],
  },
  {
    id: "prancha_lateral",
    canonicalNamePt: "Prancha lateral",
    namesByLanguage: {
      "pt-BR": "Prancha lateral",
      "it-IT": "Plank laterale",
      "en-US": "Side plank",
      "es-ES": "Plancha lateral",
    },
    aliasesByLanguage: {
      "pt-BR": ["prancha lateral", "plank lateral"],
      "it-IT": ["plank laterale"],
      "en-US": ["side plank"],
      "es-ES": ["plancha lateral"],
    },
    muscleGroup: "abdomen",
    videoUrl: `${V}/abdomen-core/prancha_lateral.mp4`,
    sourceFileName: "prancha_lateral.mp4",
    videoProvider: "local",
    movementPattern: "isometrico",
    equipment: "bodyweight",
    tags: ["core", "obliquo", "estabilizacao"],
  },

  // ─── BRAÇOS ────────────────────────────────────────────────────────────────
  {
    id: "biceps_maquina",
    canonicalNamePt: "Bíceps máquina",
    namesByLanguage: {
      "pt-BR": "Bíceps máquina",
      "it-IT": "Curl alla macchina",
      "en-US": "Machine biceps curl",
      "es-ES": "Curl bíceps en máquina",
    },
    aliasesByLanguage: {
      "pt-BR": ["rosca direta máquina", "curl máquina"],
      "it-IT": ["curl macchina"],
      "en-US": ["machine curl"],
      "es-ES": ["curl máquina"],
    },
    muscleGroup: "bracos",
    videoUrl: `${V}/bracos/biceps_maquina.mp4`,
    sourceFileName: "biceps_maquina.mp4",
    videoProvider: "local",
    movementPattern: "flexao",
    equipment: "maquina",
    tags: ["biceps", "bracos"],
  },
  {
    id: "biceps_frontal_unilateral_polia",
    canonicalNamePt: "Bíceps frontal unilateral polia",
    namesByLanguage: {
      "pt-BR": "Bíceps frontal unilateral polia",
      "it-IT": "Curl frontale unilaterale al cavo",
      "en-US": "Unilateral cable biceps curl",
      "es-ES": "Curl bíceps frontal unilateral polea",
    },
    aliasesByLanguage: {
      "pt-BR": ["rosca frontal polia", "curl unilateral frontal"],
      "it-IT": ["curl unilaterale cavo"],
      "en-US": ["cable curl unilateral"],
      "es-ES": ["curl polea unilateral"],
    },
    muscleGroup: "bracos",
    videoUrl: `${V}/bracos/bicipes_frontal_unilateral_polia.mp4`,
    sourceFileName: "bicipes_frontal_unilateral_polia.mp4",
    videoProvider: "local",
    movementPattern: "flexao",
    equipment: "polia",
    tags: ["biceps", "bracos"],
  },
  {
    id: "biceps_lateral_unilateral_polia",
    canonicalNamePt: "Bíceps lateral unilateral polia",
    namesByLanguage: {
      "pt-BR": "Bíceps lateral unilateral polia",
      "it-IT": "Curl laterale unilaterale al cavo",
      "en-US": "Lateral unilateral cable curl",
      "es-ES": "Curl bíceps lateral unilateral polea",
    },
    aliasesByLanguage: {
      "pt-BR": ["rosca lateral polia"],
      "it-IT": ["curl laterale cavo"],
      "en-US": ["lateral cable curl"],
      "es-ES": ["curl lateral polea"],
    },
    muscleGroup: "bracos",
    videoUrl: `${V}/bracos/bicipes_lateral_unilateral_polia.mp4`,
    sourceFileName: "bicipes_lateral_unilateral_polia.mp4",
    videoProvider: "local",
    movementPattern: "flexao",
    equipment: "polia",
    tags: ["biceps", "bracos"],
  },
  {
    id: "paralelas_gravitron",
    canonicalNamePt: "Paralelas gravitron",
    namesByLanguage: {
      "pt-BR": "Paralelas gravitron",
      "it-IT": "Dip assistite al gravitron",
      "en-US": "Assisted dips gravitron",
      "es-ES": "Fondos asistidos gravitron",
    },
    aliasesByLanguage: {
      "pt-BR": ["paralela assistida", "gravitron", "dip assistido"],
      "it-IT": ["dip assistite", "gravitron"],
      "en-US": ["assisted dips", "gravitron"],
      "es-ES": ["fondos asistidos", "gravitron"],
    },
    muscleGroup: "bracos",
    videoUrl: `${V}/bracos/paralelas_gravitron.mp4`,
    sourceFileName: "paralelas_gravitron.mp4",
    videoProvider: "local",
    movementPattern: "empurrar",
    equipment: "gravitron",
    tags: ["triceps", "peito", "bracos"],
  },
  {
    id: "rosca_alternada",
    canonicalNamePt: "Rosca alternada",
    namesByLanguage: {
      "pt-BR": "Rosca alternada",
      "it-IT": "Curl alternato",
      "en-US": "Alternating dumbbell curl",
      "es-ES": "Curl alternado",
    },
    aliasesByLanguage: {
      "pt-BR": ["rosca alternada", "curl alternado"],
      "it-IT": ["curl alternato"],
      "en-US": ["alternating curl"],
      "es-ES": ["curl alternado"],
    },
    muscleGroup: "bracos",
    videoUrl: `${V}/bracos/rosca_alternada.mp4`,
    sourceFileName: "rosca_alternada.mp4",
    videoProvider: "local",
    movementPattern: "flexao",
    equipment: "halter",
    tags: ["biceps", "bracos"],
  },
  {
    id: "rosca_alternada_halter_sentado",
    canonicalNamePt: "Rosca alternada halter sentado",
    namesByLanguage: {
      "pt-BR": "Rosca alternada halter sentado",
      "it-IT": "Curl alternato con manubri seduto",
      "en-US": "Seated alternating dumbbell curl",
      "es-ES": "Curl alternado mancuerna sentado",
    },
    aliasesByLanguage: {
      "pt-BR": ["rosca inclinada", "rosca sentado", "curl sentado"],
      "it-IT": ["curl alternato seduto", "curl inclinato"],
      "en-US": ["seated curl", "incline curl"],
      "es-ES": ["curl sentado", "curl inclinado"],
    },
    muscleGroup: "bracos",
    videoUrl: `${V}/bracos/rosca_alternada_halter_sentado.mp4`,
    sourceFileName: "rosca_alternada_halter_sentado.mp4",
    videoProvider: "local",
    movementPattern: "flexao",
    equipment: "halter",
    tags: ["biceps", "bracos"],
  },
  {
    id: "rosca_martelo_alternada",
    canonicalNamePt: "Rosca martelo alternada",
    namesByLanguage: {
      "pt-BR": "Rosca martelo alternada",
      "it-IT": "Curl martello alternato",
      "en-US": "Alternating hammer curl",
      "es-ES": "Curl martillo alternado",
    },
    aliasesByLanguage: {
      "pt-BR": ["rosca martelo", "hammer curl"],
      "it-IT": ["curl martello"],
      "en-US": ["hammer curl"],
      "es-ES": ["curl martillo"],
    },
    muscleGroup: "bracos",
    videoUrl: `${V}/bracos/rosca_martelo_alternada.mp4`,
    sourceFileName: "rosca_martelo_alternada.mp4",
    videoProvider: "local",
    movementPattern: "flexao",
    equipment: "halter",
    tags: ["biceps", "bracos"],
  },
  {
    id: "rosca_polia_corda",
    canonicalNamePt: "Rosca polia corda",
    namesByLanguage: {
      "pt-BR": "Rosca polia corda",
      "it-IT": "Curl al cavo con corda",
      "en-US": "Cable rope curl",
      "es-ES": "Curl polea cuerda",
    },
    aliasesByLanguage: {
      "pt-BR": ["rosca corda", "curl corda"],
      "it-IT": ["curl cavo corda"],
      "en-US": ["rope curl"],
      "es-ES": ["curl cuerda"],
    },
    muscleGroup: "bracos",
    videoUrl: `${V}/bracos/rosca_polia_corda.mp4`,
    sourceFileName: "rosca_polia_corda.mp4",
    videoProvider: "local",
    movementPattern: "flexao",
    equipment: "polia",
    tags: ["biceps", "bracos"],
  },
  {
    id: "rosca_unilateral_halter_sentado",
    canonicalNamePt: "Rosca unilateral halter sentado",
    namesByLanguage: {
      "pt-BR": "Rosca unilateral halter sentado",
      "it-IT": "Curl unilaterale con manubrio seduto",
      "en-US": "Seated unilateral dumbbell curl",
      "es-ES": "Curl unilateral mancuerna sentado",
    },
    aliasesByLanguage: {
      "pt-BR": ["rosca unilateral sentado"],
      "it-IT": ["curl unilaterale seduto"],
      "en-US": ["unilateral seated curl"],
      "es-ES": ["curl unilateral sentado"],
    },
    muscleGroup: "bracos",
    videoUrl: `${V}/bracos/rosca_unilareal_halter_sentado.mp4`,
    sourceFileName: "rosca_unilareal_halter_sentado.mp4",
    videoProvider: "local",
    movementPattern: "flexao",
    equipment: "halter",
    tags: ["biceps", "bracos"],
  },
  {
    id: "triceps_barra_v_cabo",
    canonicalNamePt: "Tríceps barra V cabo",
    namesByLanguage: {
      "pt-BR": "Tríceps barra V cabo",
      "it-IT": "Pushdown barra V al cavo",
      "en-US": "Cable V-bar triceps pushdown",
      "es-ES": "Pushdown barra V cable",
    },
    aliasesByLanguage: {
      "pt-BR": ["tríceps corda", "tríceps barra v", "pushdown"],
      "it-IT": ["pushdown barra v", "tricipite cavo"],
      "en-US": ["v-bar pushdown", "triceps pushdown"],
      "es-ES": ["pushdown barra v", "tríceps cable"],
    },
    muscleGroup: "bracos",
    videoUrl: `${V}/bracos/triceps_barra_v_cabo.mp4`,
    sourceFileName: "triceps_barra_v_cabo.mp4",
    videoProvider: "local",
    movementPattern: "extensao",
    equipment: "polia",
    tags: ["triceps", "bracos"],
  },
  {
    id: "triceps_coice_cabo",
    canonicalNamePt: "Tríceps coice cabo",
    namesByLanguage: {
      "pt-BR": "Tríceps coice cabo",
      "it-IT": "Kickback al cavo",
      "en-US": "Cable triceps kickback",
      "es-ES": "Tríceps patada cable",
    },
    aliasesByLanguage: {
      "pt-BR": ["coice tríceps", "kickback cabo"],
      "it-IT": ["kickback cavo"],
      "en-US": ["cable kickback"],
      "es-ES": ["patada triceps cable"],
    },
    muscleGroup: "bracos",
    videoUrl: `${V}/bracos/triceps_coice_cabo.mp4`,
    sourceFileName: "triceps_coice_cabo.mp4",
    videoProvider: "local",
    movementPattern: "extensao",
    equipment: "polia",
    tags: ["triceps", "bracos"],
  },
  {
    id: "triceps_coice_halter_banco",
    canonicalNamePt: "Tríceps coice halter apoio banco",
    namesByLanguage: {
      "pt-BR": "Tríceps coice halter apoio banco",
      "it-IT": "Kickback con manubrio appoggiato alla panca",
      "en-US": "Dumbbell kickback on bench",
      "es-ES": "Tríceps patada mancuerna apoyo banco",
    },
    aliasesByLanguage: {
      "pt-BR": ["coice halter banco", "kickback halter"],
      "it-IT": ["kickback manubrio"],
      "en-US": ["dumbbell kickback"],
      "es-ES": ["patada mancuerna"],
    },
    muscleGroup: "bracos",
    videoUrl: `${V}/bracos/triceps_coice_halter_apoio_banco.mp4`,
    sourceFileName: "triceps_coice_halter_apoio_banco.mp4",
    videoProvider: "local",
    movementPattern: "extensao",
    equipment: "halter",
    tags: ["triceps", "bracos"],
  },
  {
    id: "triceps_frances_cabo",
    canonicalNamePt: "Tríceps francês cabo",
    namesByLanguage: {
      "pt-BR": "Tríceps francês cabo",
      "it-IT": "French press al cavo",
      "en-US": "Cable overhead triceps extension",
      "es-ES": "Extensión tríceps francés cable",
    },
    aliasesByLanguage: {
      "pt-BR": ["tríceps francês", "french press cabo"],
      "it-IT": ["french press cavo", "tricipite overhead"],
      "en-US": ["overhead cable extension", "french press cable"],
      "es-ES": ["extensión overhead", "tríceps francés"],
    },
    muscleGroup: "bracos",
    videoUrl: `${V}/bracos/triceps_frances_cabo.mp4`,
    sourceFileName: "triceps_frances_cabo.mp4",
    videoProvider: "local",
    movementPattern: "extensao",
    equipment: "polia",
    tags: ["triceps", "bracos"],
  },
  {
    id: "triceps_polia_alta",
    canonicalNamePt: "Tríceps polia alta",
    namesByLanguage: {
      "pt-BR": "Tríceps polia alta",
      "it-IT": "Estensione tricipite polia alta",
      "en-US": "High cable triceps extension",
      "es-ES": "Extensión tríceps polea alta",
    },
    aliasesByLanguage: {
      "pt-BR": ["tríceps polia", "polia alta tríceps"],
      "it-IT": ["tricipite polia alta"],
      "en-US": ["high cable extension"],
      "es-ES": ["polea alta tríceps"],
    },
    muscleGroup: "bracos",
    videoUrl: `${V}/bracos/triceps_frences_polia_alta.mp4`,
    sourceFileName: "triceps_frences_polia_alta.mp4",
    videoProvider: "local",
    movementPattern: "extensao",
    equipment: "polia",
    tags: ["triceps", "bracos"],
  },
  {
    id: "triceps_martelo_maquina",
    canonicalNamePt: "Tríceps martelo máquina",
    namesByLanguage: {
      "pt-BR": "Tríceps martelo máquina",
      "it-IT": "Tricipite martello alla macchina",
      "en-US": "Machine hammer triceps",
      "es-ES": "Tríceps martillo máquina",
    },
    aliasesByLanguage: {
      "pt-BR": ["martelo máquina", "tríceps máquina martelo"],
      "it-IT": ["tricipite macchina martello"],
      "en-US": ["machine triceps hammer"],
      "es-ES": ["martillo máquina tríceps"],
    },
    muscleGroup: "bracos",
    videoUrl: `${V}/bracos/triceps_martelo_maquina.mp4`,
    sourceFileName: "triceps_martelo_maquina.mp4",
    videoProvider: "local",
    movementPattern: "extensao",
    equipment: "maquina",
    tags: ["triceps", "bracos"],
  },
  {
    id: "triceps_testa_barra",
    canonicalNamePt: "Tríceps testa barra",
    namesByLanguage: {
      "pt-BR": "Tríceps testa barra",
      "it-IT": "French press con bilanciere",
      "en-US": "EZ bar skull crusher",
      "es-ES": "Tríceps testa barra",
    },
    aliasesByLanguage: {
      "pt-BR": ["skull crusher", "testa barra"],
      "it-IT": ["skull crusher", "french press bilanciere"],
      "en-US": ["skull crusher", "lying triceps extension"],
      "es-ES": ["rompecráneos", "skull crusher"],
    },
    muscleGroup: "bracos",
    videoUrl: `${V}/bracos/triceps_testa_barra.mp4`,
    sourceFileName: "triceps_testa_barra.mp4",
    videoProvider: "local",
    movementPattern: "extensao",
    equipment: "barra",
    tags: ["triceps", "bracos"],
  },

  // ─── COSTAS ────────────────────────────────────────────────────────────────
  {
    id: "crucifixo_inverso_maquina",
    canonicalNamePt: "Crucifixo inverso máquina",
    namesByLanguage: {
      "pt-BR": "Crucifixo inverso máquina",
      "it-IT": "Croci inverse alla macchina",
      "en-US": "Reverse fly machine",
      "es-ES": "Crucifijo inverso máquina",
    },
    aliasesByLanguage: {
      "pt-BR": ["crucifixo inverso", "voador inverso"],
      "it-IT": ["croci inverse", "pec deck inverso"],
      "en-US": ["reverse fly", "rear delt machine"],
      "es-ES": ["crucifijo inverso", "pec deck inverso"],
    },
    muscleGroup: "costas",
    videoUrl: `${V}/costas/crucifixo_inverso_maquina.mp4`,
    sourceFileName: "crucifixo_inverso_maquina.mp4",
    videoProvider: "local",
    movementPattern: "puxar",
    equipment: "maquina",
    tags: ["costas", "deltoides-posterior"],
  },
  {
    id: "puxada_atras_maquina",
    canonicalNamePt: "Puxada atrás máquina",
    namesByLanguage: {
      "pt-BR": "Puxada atrás máquina",
      "it-IT": "Lat machine dietro",
      "en-US": "Behind-the-neck lat pulldown",
      "es-ES": "Jalón detrás en máquina",
    },
    aliasesByLanguage: {
      "pt-BR": ["puxada atrás", "lat machine atrás"],
      "it-IT": ["lat machine dietro"],
      "en-US": ["behind-neck pulldown"],
      "es-ES": ["jalón detrás"],
    },
    muscleGroup: "costas",
    videoUrl: `${V}/costas/puxada_atras_maquina.mp4`,
    sourceFileName: "puxada_atras_maquina.mp4",
    videoProvider: "local",
    movementPattern: "puxar",
    equipment: "maquina",
    tags: ["costas", "dorsais"],
  },
  {
    id: "puxada_frente",
    canonicalNamePt: "Puxada frente",
    namesByLanguage: {
      "pt-BR": "Puxada frente",
      "it-IT": "Lat machine avanti",
      "en-US": "Lat pulldown",
      "es-ES": "Jalón al pecho",
    },
    aliasesByLanguage: {
      "pt-BR": ["puxada frente", "lat machine frente", "pulley frente"],
      "it-IT": ["lat machine", "pulley alto"],
      "en-US": ["lat pulldown", "cable pulldown"],
      "es-ES": ["jalón al pecho", "polea alta"],
    },
    muscleGroup: "costas",
    videoUrl: `${V}/costas/puxada_frente.mp4`,
    sourceFileName: "puxada_frente.mp4",
    videoProvider: "local",
    movementPattern: "puxar",
    equipment: "maquina",
    tags: ["costas", "dorsais"],
  },
  {
    id: "remada_baixa_polia",
    canonicalNamePt: "Remada baixa polia",
    namesByLanguage: {
      "pt-BR": "Remada baixa polia",
      "it-IT": "Rematore basso al cavo",
      "en-US": "Seated cable row",
      "es-ES": "Remo bajo en polea",
    },
    aliasesByLanguage: {
      "pt-BR": ["remada baixa", "polia baixa", "remada sentado"],
      "it-IT": ["rematore basso", "remo cavo basso"],
      "en-US": ["cable row", "seated row"],
      "es-ES": ["remo bajo", "remo sentado"],
    },
    muscleGroup: "costas",
    videoUrl: `${V}/costas/remada_baixa_polia.mp4`,
    sourceFileName: "remada_baixa_polia.mp4",
    videoProvider: "local",
    movementPattern: "puxar",
    equipment: "polia",
    tags: ["costas"],
  },
  {
    id: "remada_cavalinho",
    canonicalNamePt: "Remada cavalinho",
    namesByLanguage: {
      "pt-BR": "Remada cavalinho",
      "it-IT": "Rematore con busto inclinato",
      "en-US": "Bent-over row",
      "es-ES": "Remo inclinado",
    },
    aliasesByLanguage: {
      "pt-BR": ["remada curvada", "cavalinho", "bent over row"],
      "it-IT": ["rematore inclinato", "bent over row"],
      "en-US": ["bent-over row", "barbell row"],
      "es-ES": ["remo inclinado", "remo con barra"],
    },
    muscleGroup: "costas",
    videoUrl: `${V}/costas/remada_cavalinho.mp4`,
    sourceFileName: "remada_cavalinho.mp4",
    videoProvider: "local",
    movementPattern: "puxar",
    equipment: "barra",
    tags: ["costas"],
  },
  {
    id: "remada_frontal_cross",
    canonicalNamePt: "Remada frontal cross",
    namesByLanguage: {
      "pt-BR": "Remada frontal cross",
      "it-IT": "Rematore frontale al cavo",
      "en-US": "Cable front row",
      "es-ES": "Remo frontal cable",
    },
    aliasesByLanguage: {
      "pt-BR": ["remada frontal", "cross frontal"],
      "it-IT": ["remo frontale cavo"],
      "en-US": ["cable front row"],
      "es-ES": ["remo frontal"],
    },
    muscleGroup: "costas",
    videoUrl: `${V}/costas/remada_frontal_cross.mp4`,
    sourceFileName: "remada_frontal_cross.mp4",
    videoProvider: "local",
    movementPattern: "puxar",
    equipment: "polia",
    tags: ["costas"],
  },
  {
    id: "remada_neutra_maquina",
    canonicalNamePt: "Remada neutra máquina",
    namesByLanguage: {
      "pt-BR": "Remada neutra máquina",
      "it-IT": "Rematore neutro alla macchina",
      "en-US": "Neutral grip machine row",
      "es-ES": "Remo neutro máquina",
    },
    aliasesByLanguage: {
      "pt-BR": ["remada neutra", "remada máquina"],
      "it-IT": ["rematore neutro macchina"],
      "en-US": ["machine row", "neutral row"],
      "es-ES": ["remo neutro", "remo máquina"],
    },
    muscleGroup: "costas",
    videoUrl: `${V}/costas/remada_neutra_maquina.mp4`,
    sourceFileName: "remada_neutra_maquina.mp4",
    videoProvider: "local",
    movementPattern: "puxar",
    equipment: "maquina",
    tags: ["costas"],
  },

  // ─── OMBRO ─────────────────────────────────────────────────────────────────
  {
    id: "desenvolvimento_sentado",
    canonicalNamePt: "Desenvolvimento sentado",
    namesByLanguage: {
      "pt-BR": "Desenvolvimento sentado",
      "it-IT": "Military press seduto",
      "en-US": "Seated shoulder press",
      "es-ES": "Press militar sentado",
    },
    aliasesByLanguage: {
      "pt-BR": ["desenvolvimento", "military press", "press ombro"],
      "it-IT": ["military press", "press spalle"],
      "en-US": ["shoulder press", "military press"],
      "es-ES": ["press hombros", "press militar"],
    },
    muscleGroup: "ombro",
    videoUrl: `${V}/ombro/desenvolvimento_sentado.mp4`,
    sourceFileName: "desenvolvimento_sentado.mp4",
    videoProvider: "local",
    movementPattern: "empurrar",
    equipment: "halter",
    tags: ["ombro", "deltoides"],
  },
  {
    id: "elevacao_frontal_anilha",
    canonicalNamePt: "Elevação frontal anilha",
    namesByLanguage: {
      "pt-BR": "Elevação frontal anilha",
      "it-IT": "Alzate frontali con disco",
      "en-US": "Plate front raise",
      "es-ES": "Elevación frontal con disco",
    },
    aliasesByLanguage: {
      "pt-BR": ["frontal anilha", "elevação frontal disco"],
      "it-IT": ["alzate frontali disco"],
      "en-US": ["plate front raise", "disc front raise"],
      "es-ES": ["elevación frontal disco"],
    },
    muscleGroup: "ombro",
    videoUrl: `${V}/ombro/elevacao_frontal_anilha.mp4`,
    sourceFileName: "elevacao_frontal_anilha.mp4",
    videoProvider: "local",
    movementPattern: "elevacao",
    equipment: "anilha",
    tags: ["ombro", "deltoides-anterior"],
  },
  {
    id: "elevacao_frontal_sentado_barra",
    canonicalNamePt: "Elevação frontal sentado barra",
    namesByLanguage: {
      "pt-BR": "Elevação frontal sentado barra",
      "it-IT": "Alzate frontali seduto con bilanciere",
      "en-US": "Seated barbell front raise",
      "es-ES": "Elevación frontal sentado barra",
    },
    aliasesByLanguage: {
      "pt-BR": ["frontal sentado", "elevação frontal barra"],
      "it-IT": ["alzate frontali seduto"],
      "en-US": ["seated front raise", "barbell front raise"],
      "es-ES": ["frontal sentado barra"],
    },
    muscleGroup: "ombro",
    videoUrl: `${V}/ombro/elevacao_frontal_sentado_barra.mp4`,
    sourceFileName: "elevacao_frontal_sentado_barra.mp4",
    videoProvider: "local",
    movementPattern: "elevacao",
    equipment: "barra",
    tags: ["ombro", "deltoides-anterior"],
  },
  {
    id: "elevacao_lateral_halter_sentado",
    canonicalNamePt: "Elevação lateral halter sentado",
    namesByLanguage: {
      "pt-BR": "Elevação lateral halter sentado",
      "it-IT": "Alzate laterali seduto con manubri",
      "en-US": "Seated dumbbell lateral raise",
      "es-ES": "Elevación lateral sentado mancuerna",
    },
    aliasesByLanguage: {
      "pt-BR": ["lateral sentado", "elevação lateral sentado"],
      "it-IT": ["alzate laterali seduto"],
      "en-US": ["seated lateral raise"],
      "es-ES": ["elevación lateral sentado"],
    },
    muscleGroup: "ombro",
    videoUrl: `${V}/ombro/elevacao_lateral_halter_sentado.mp4`,
    sourceFileName: "elevacao_lateral_halter_sentado.mp4",
    videoProvider: "local",
    movementPattern: "elevacao",
    equipment: "halter",
    tags: ["ombro", "deltoides-lateral"],
  },
  {
    id: "elevacao_lateral_simultanea_sentado",
    canonicalNamePt: "Elevação lateral simultânea sentado",
    namesByLanguage: {
      "pt-BR": "Elevação lateral simultânea sentado",
      "it-IT": "Alzate laterali simultanee seduto",
      "en-US": "Simultaneous seated lateral raise",
      "es-ES": "Elevación lateral simultánea sentado",
    },
    aliasesByLanguage: {
      "pt-BR": ["lateral simultâneo sentado"],
      "it-IT": ["alzate laterali contemporanee"],
      "en-US": ["bilateral lateral raise seated"],
      "es-ES": ["lateral simultáneo sentado"],
    },
    muscleGroup: "ombro",
    videoUrl: `${V}/ombro/elevacao_lateral_simultanea_sentado.mp4`,
    sourceFileName: "elevacao_lateral_simultanea_sentado.mp4",
    videoProvider: "local",
    movementPattern: "elevacao",
    equipment: "halter",
    tags: ["ombro", "deltoides-lateral"],
  },
  {
    id: "elevacao_lateral_unilateral_banco",
    canonicalNamePt: "Elevação lateral unilateral banco",
    namesByLanguage: {
      "pt-BR": "Elevação lateral unilateral banco",
      "it-IT": "Alzata laterale unilaterale alla panca",
      "en-US": "Unilateral lateral raise on bench",
      "es-ES": "Elevación lateral unilateral en banco",
    },
    aliasesByLanguage: {
      "pt-BR": ["lateral unilateral banco"],
      "it-IT": ["alzata laterale unilaterale"],
      "en-US": ["unilateral lateral raise"],
      "es-ES": ["lateral unilateral banco"],
    },
    muscleGroup: "ombro",
    videoUrl: `${V}/ombro/elevacao_lateral_unilateral_banco.mp4`,
    sourceFileName: "elevacao_lateral_unilateral_banco.mp4",
    videoProvider: "local",
    movementPattern: "elevacao",
    equipment: "halter",
    tags: ["ombro", "deltoides-lateral"],
  },
  {
    id: "remada_alta_com_elevacao_halter_sentado",
    canonicalNamePt: "Remada alta com elevação halter sentado",
    namesByLanguage: {
      "pt-BR": "Remada alta com elevação halter sentado",
      "it-IT": "Remata alta con elevazione con manubri seduto",
      "en-US": "Upright row with lateral raise seated",
      "es-ES": "Remo al cuello con elevación sentado",
    },
    aliasesByLanguage: {
      "pt-BR": ["remada alta elevação sentado"],
      "it-IT": ["remata alta elevazione"],
      "en-US": ["upright row lateral raise"],
      "es-ES": ["remo cuello elevación"],
    },
    muscleGroup: "ombro",
    videoUrl: `${V}/ombro/remada_alta_com_elevacao_halter_sentado.mp4`,
    sourceFileName: "remada_alta_com_elevacao_halter_sentado.mp4",
    videoProvider: "local",
    movementPattern: "elevacao",
    equipment: "halter",
    tags: ["ombro", "deltoides"],
  },
  {
    id: "remada_alta_guiada",
    canonicalNamePt: "Remada alta guiada",
    namesByLanguage: {
      "pt-BR": "Remada alta guiada",
      "it-IT": "Remata alta guidata",
      "en-US": "Guided upright row",
      "es-ES": "Remo al cuello guiado",
    },
    aliasesByLanguage: {
      "pt-BR": ["remada alta smith", "upright row guiado"],
      "it-IT": ["remata alta guidata"],
      "en-US": ["machine upright row"],
      "es-ES": ["remo cuello guiado"],
    },
    muscleGroup: "ombro",
    videoUrl: `${V}/ombro/remada_alta_guiada.mp4`,
    sourceFileName: "remada_alta_guiada.mp4",
    videoProvider: "local",
    movementPattern: "puxar",
    equipment: "maquina",
    tags: ["ombro", "trapezio"],
  },
  {
    id: "remada_alta_halter",
    canonicalNamePt: "Remada alta halter",
    namesByLanguage: {
      "pt-BR": "Remada alta halter",
      "it-IT": "Remata alta con manubri",
      "en-US": "Dumbbell upright row",
      "es-ES": "Remo al cuello mancuerna",
    },
    aliasesByLanguage: {
      "pt-BR": ["remada alta", "upright row"],
      "it-IT": ["remata alta manubri"],
      "en-US": ["upright row"],
      "es-ES": ["remo cuello"],
    },
    muscleGroup: "ombro",
    videoUrl: `${V}/ombro/remada_alta_halter.mp4`,
    sourceFileName: "remada_alta_halter.mp4",
    videoProvider: "local",
    movementPattern: "puxar",
    equipment: "halter",
    tags: ["ombro", "trapezio"],
  },
  {
    id: "serrote",
    canonicalNamePt: "Serrote",
    namesByLanguage: {
      "pt-BR": "Serrote",
      "it-IT": "Rematore a un braccio",
      "en-US": "One-arm dumbbell row",
      "es-ES": "Remo a una mano",
    },
    aliasesByLanguage: {
      "pt-BR": ["serrote", "remada unilateral", "one arm row"],
      "it-IT": ["rematore unilaterale", "one arm row"],
      "en-US": ["one-arm row", "single arm row"],
      "es-ES": ["remo una mano", "remo unilateral"],
    },
    muscleGroup: "ombro",
    videoUrl: `${V}/ombro/serrote.mp4`,
    sourceFileName: "serrote.mp4",
    videoProvider: "local",
    movementPattern: "puxar",
    equipment: "halter",
    tags: ["costas", "ombro"],
  },

  // ─── PEITO ─────────────────────────────────────────────────────────────────
  {
    id: "crucifixo_maquina",
    canonicalNamePt: "Crucifixo máquina",
    namesByLanguage: {
      "pt-BR": "Crucifixo máquina",
      "it-IT": "Croci alla macchina",
      "en-US": "Machine fly",
      "es-ES": "Crucifijo en máquina",
    },
    aliasesByLanguage: {
      "pt-BR": ["crossover", "voador", "pec deck", "crucifixo"],
      "it-IT": ["croci macchina", "pec deck"],
      "en-US": ["machine fly", "pec deck"],
      "es-ES": ["crucifijo máquina", "pec deck"],
    },
    muscleGroup: "peito",
    videoUrl: `${V}/peito/crucifixo_maquina.mp4`,
    sourceFileName: "crucifixo_maquina.mp4",
    videoProvider: "local",
    movementPattern: "adducao",
    equipment: "maquina",
    tags: ["peito"],
  },
  {
    id: "flexao",
    canonicalNamePt: "Flexão",
    namesByLanguage: {
      "pt-BR": "Flexão",
      "it-IT": "Flessioni",
      "en-US": "Push-up",
      "es-ES": "Flexión",
    },
    aliasesByLanguage: {
      "pt-BR": ["flexão", "flexao", "push-up"],
      "it-IT": ["flessioni", "push up"],
      "en-US": ["push-up", "push up"],
      "es-ES": ["flexión", "push-up"],
    },
    muscleGroup: "peito",
    videoUrl: `${V}/peito/flexao.mp4`,
    sourceFileName: "flexao.mp4",
    videoProvider: "local",
    movementPattern: "empurrar",
    equipment: "bodyweight",
    tags: ["peito", "triceps", "corpo-livre"],
  },
  {
    id: "supino_baixo_maquina",
    canonicalNamePt: "Supino baixo máquina",
    namesByLanguage: {
      "pt-BR": "Supino baixo máquina",
      "it-IT": "Chest press bassa alla macchina",
      "en-US": "Low machine chest press",
      "es-ES": "Press de pecho bajo en máquina",
    },
    aliasesByLanguage: {
      "pt-BR": ["supino baixo", "chest press baixo"],
      "it-IT": ["chest press bassa"],
      "en-US": ["low chest press"],
      "es-ES": ["press pecho bajo"],
    },
    muscleGroup: "peito",
    videoUrl: `${V}/peito/supino_baixo_maquina.mp4`,
    sourceFileName: "supino_baixo_maquina.mp4",
    videoProvider: "local",
    movementPattern: "empurrar",
    equipment: "maquina",
    tags: ["peito"],
  },
  {
    id: "supino_declinado",
    canonicalNamePt: "Supino declinado",
    namesByLanguage: {
      "pt-BR": "Supino declinado",
      "it-IT": "Panca declinata",
      "en-US": "Decline bench press",
      "es-ES": "Press declinado",
    },
    aliasesByLanguage: {
      "pt-BR": ["supino declinado", "decline press"],
      "it-IT": ["panca declinata"],
      "en-US": ["decline press", "decline bench"],
      "es-ES": ["press declinado", "banco declinado"],
    },
    muscleGroup: "peito",
    videoUrl: `${V}/peito/supino_declinado.mp4`,
    sourceFileName: "supino_declinado.mp4",
    videoProvider: "local",
    movementPattern: "empurrar",
    equipment: "barra",
    tags: ["peito"],
  },
  {
    id: "supino_inclinado",
    canonicalNamePt: "Supino inclinado",
    namesByLanguage: {
      "pt-BR": "Supino inclinado",
      "it-IT": "Panca inclinata",
      "en-US": "Incline bench press",
      "es-ES": "Press inclinado",
    },
    aliasesByLanguage: {
      "pt-BR": ["supino inclinado", "incline press"],
      "it-IT": ["panca inclinata", "incline press"],
      "en-US": ["incline press", "incline bench"],
      "es-ES": ["press inclinado", "banco inclinado"],
    },
    muscleGroup: "peito",
    videoUrl: `${V}/peito/supino_inclinado.mp4`,
    sourceFileName: "supino_inclinado.mp4",
    videoProvider: "local",
    movementPattern: "empurrar",
    equipment: "barra",
    tags: ["peito"],
  },
  {
    id: "supino_inclinado_cross_bilateral",
    canonicalNamePt: "Supino inclinado cross bilateral",
    namesByLanguage: {
      "pt-BR": "Supino inclinado cross bilateral",
      "it-IT": "Panca inclinata ai cavi bilaterale",
      "en-US": "Bilateral incline cable press",
      "es-ES": "Press inclinado cable bilateral",
    },
    aliasesByLanguage: {
      "pt-BR": ["cross bilateral inclinado"],
      "it-IT": ["panca inclinata cavi"],
      "en-US": ["incline cable press"],
      "es-ES": ["press inclinado cable"],
    },
    muscleGroup: "peito",
    videoUrl: `${V}/peito/supino_inclinado_cross_bilateral.mp4`,
    sourceFileName: "supino_inclinado_cross_bilateral.mp4",
    videoProvider: "local",
    movementPattern: "empurrar",
    equipment: "polia",
    tags: ["peito"],
  },
  {
    id: "supino_inclinado_halter",
    canonicalNamePt: "Supino inclinado halter",
    namesByLanguage: {
      "pt-BR": "Supino inclinado halter",
      "it-IT": "Panca inclinata con manubri",
      "en-US": "Incline dumbbell press",
      "es-ES": "Press inclinado mancuerna",
    },
    aliasesByLanguage: {
      "pt-BR": ["inclinado halter", "supino inclinado halteres"],
      "it-IT": ["panca inclinata manubri"],
      "en-US": ["incline dumbbell", "incline db press"],
      "es-ES": ["press inclinado mancuernas"],
    },
    muscleGroup: "peito",
    videoUrl: `${V}/peito/supino_inclinado_halter.mp4`,
    sourceFileName: "supino_inclinado_halter.mp4",
    videoProvider: "local",
    movementPattern: "empurrar",
    equipment: "halter",
    tags: ["peito"],
  },
  {
    id: "supino_reto",
    canonicalNamePt: "Supino reto",
    namesByLanguage: {
      "pt-BR": "Supino reto",
      "it-IT": "Panca piana",
      "en-US": "Flat bench press",
      "es-ES": "Press banca plano",
    },
    aliasesByLanguage: {
      "pt-BR": ["supino reto", "supino", "bench press"],
      "it-IT": ["panca piana", "bench press"],
      "en-US": ["bench press", "flat bench"],
      "es-ES": ["press de banca", "bench press"],
    },
    muscleGroup: "peito",
    videoUrl: `${V}/peito/supino_reto.mp4`,
    sourceFileName: "supino_reto.mp4",
    videoProvider: "local",
    movementPattern: "empurrar",
    equipment: "barra",
    tags: ["peito"],
  },
  {
    id: "supino_reto_cross_bilateral",
    canonicalNamePt: "Supino reto cross bilateral",
    namesByLanguage: {
      "pt-BR": "Supino reto cross bilateral",
      "it-IT": "Panca piana ai cavi bilaterale",
      "en-US": "Bilateral flat cable press",
      "es-ES": "Press plano cable bilateral",
    },
    aliasesByLanguage: {
      "pt-BR": ["cross bilateral reto", "supino reto cabo"],
      "it-IT": ["panca piana cavi"],
      "en-US": ["flat cable press"],
      "es-ES": ["press plano cable"],
    },
    muscleGroup: "peito",
    videoUrl: `${V}/peito/supino_reto_cross_bilateral.mp4`,
    sourceFileName: "supino_reto_cross_bilateral.mp4",
    videoProvider: "local",
    movementPattern: "empurrar",
    equipment: "polia",
    tags: ["peito"],
  },
  {
    id: "supino_reto_fechado_halter",
    canonicalNamePt: "Supino reto fechado halter",
    namesByLanguage: {
      "pt-BR": "Supino reto fechado halter",
      "it-IT": "Panca piana presa stretta con manubri",
      "en-US": "Close-grip dumbbell press",
      "es-ES": "Press plano agarre cerrado mancuerna",
    },
    aliasesByLanguage: {
      "pt-BR": ["supino fechado halter", "close grip halter"],
      "it-IT": ["panca piana presa stretta"],
      "en-US": ["close grip dumbbell press"],
      "es-ES": ["press agarre cerrado"],
    },
    muscleGroup: "peito",
    videoUrl: `${V}/peito/supino_reto_fechado_halter.mp4`,
    sourceFileName: "supino_reto_fechado_halter.mp4",
    videoProvider: "local",
    movementPattern: "empurrar",
    equipment: "halter",
    tags: ["peito", "triceps"],
  },
  {
    id: "supino_reto_maquina",
    canonicalNamePt: "Supino reto máquina",
    namesByLanguage: {
      "pt-BR": "Supino reto máquina",
      "it-IT": "Chest press alla macchina",
      "en-US": "Machine flat press",
      "es-ES": "Press plano en máquina",
    },
    aliasesByLanguage: {
      "pt-BR": ["chest press", "supino máquina", "chest press máquina"],
      "it-IT": ["chest press macchina"],
      "en-US": ["machine chest press", "chest press machine"],
      "es-ES": ["press pecho máquina", "chest press"],
    },
    muscleGroup: "peito",
    videoUrl: `${V}/peito/supino_reto_maquina.mp4`,
    sourceFileName: "supino_reto_maquina.mp4",
    videoProvider: "local",
    movementPattern: "empurrar",
    equipment: "maquina",
    tags: ["peito"],
  },

  // ─── PERNAS / GLÚTEOS / PANTURRILHA ────────────────────────────────────────
  {
    id: "aducao_abducao_elevacao_quadril",
    canonicalNamePt: "Adução e abdução com elevação de quadril",
    namesByLanguage: {
      "pt-BR": "Adução e abdução com elevação de quadril",
      "it-IT": "Adduzione e abduzione con elevazione del bacino",
      "en-US": "Hip raise with abduction and adduction",
      "es-ES": "Aducción y abducción con elevación de cadera",
    },
    aliasesByLanguage: {
      "pt-BR": ["adução abdução elevação"],
      "it-IT": ["adduzione abduzione elevazione"],
      "en-US": ["hip raise abduction"],
      "es-ES": ["aducción abducción elevación"],
    },
    muscleGroup: "pernas",
    videoUrl: `${V}/pernas-gluteos-panturrilha/aducao_abducao_com_elevacao_de_quadril.mp4`,
    sourceFileName: "aducao_abducao_com_elevacao_de_quadril.mp4",
    videoProvider: "local",
    movementPattern: "glutes",
    equipment: "bodyweight",
    tags: ["gluteos", "pernas"],
  },
  {
    id: "afundo_halter",
    canonicalNamePt: "Afundo halter",
    namesByLanguage: {
      "pt-BR": "Afundo halter",
      "it-IT": "Affondo con manubri",
      "en-US": "Dumbbell lunge",
      "es-ES": "Zancada mancuerna",
    },
    aliasesByLanguage: {
      "pt-BR": ["afundo", "afundo caminhando", "lunge halter"],
      "it-IT": ["affondo manubri", "lunge"],
      "en-US": ["lunge", "walking lunge"],
      "es-ES": ["zancada", "lunge mancuerna"],
    },
    muscleGroup: "pernas",
    videoUrl: `${V}/pernas-gluteos-panturrilha/afundo_halter.mp4`,
    sourceFileName: "afundo_halter.mp4",
    videoProvider: "local",
    movementPattern: "unilateral",
    equipment: "halter",
    tags: ["pernas", "gluteos"],
  },
  {
    id: "afundo_smith",
    canonicalNamePt: "Afundo smith",
    namesByLanguage: {
      "pt-BR": "Afundo smith",
      "it-IT": "Affondo al multipower",
      "en-US": "Smith machine lunge",
      "es-ES": "Zancada en multipower",
    },
    aliasesByLanguage: {
      "pt-BR": ["afundo smith", "lunge smith"],
      "it-IT": ["affondo multipower"],
      "en-US": ["smith lunge"],
      "es-ES": ["zancada smith"],
    },
    muscleGroup: "pernas",
    videoUrl: `${V}/pernas-gluteos-panturrilha/afundo_smith.mp4`,
    sourceFileName: "afundo_smith.mp4",
    videoProvider: "local",
    movementPattern: "unilateral",
    equipment: "smith",
    tags: ["pernas", "gluteos"],
  },
  {
    id: "agachamento_halter_abaixo",
    canonicalNamePt: "Agachamento halter abaixo",
    namesByLanguage: {
      "pt-BR": "Agachamento halter abaixo",
      "it-IT": "Squat con manubrio basso",
      "en-US": "Goblet squat low",
      "es-ES": "Sentadilla goblet baja",
    },
    aliasesByLanguage: {
      "pt-BR": ["goblet squat", "agachamento goblet"],
      "it-IT": ["squat manubrio basso", "goblet squat"],
      "en-US": ["goblet squat"],
      "es-ES": ["sentadilla goblet"],
    },
    muscleGroup: "pernas",
    videoUrl: `${V}/pernas-gluteos-panturrilha/agachamanto_halter_abaixo.mp4`,
    sourceFileName: "agachamanto_halter_abaixo.mp4",
    videoProvider: "local",
    movementPattern: "agachamento",
    equipment: "halter",
    tags: ["pernas", "gluteos"],
  },
  {
    id: "agachamento_halter_frente",
    canonicalNamePt: "Agachamento halter frente",
    namesByLanguage: {
      "pt-BR": "Agachamento halter frente",
      "it-IT": "Squat con manubrio frontale",
      "en-US": "Front dumbbell squat",
      "es-ES": "Sentadilla mancuerna al frente",
    },
    aliasesByLanguage: {
      "pt-BR": ["agachamento frontal halter"],
      "it-IT": ["squat frontale manubrio"],
      "en-US": ["front squat dumbbell"],
      "es-ES": ["sentadilla frontal mancuerna"],
    },
    muscleGroup: "pernas",
    videoUrl: `${V}/pernas-gluteos-panturrilha/agachamanto_halter_frente.mp4`,
    sourceFileName: "agachamanto_halter_frente.mp4",
    videoProvider: "local",
    movementPattern: "agachamento",
    equipment: "halter",
    tags: ["pernas", "gluteos"],
  },
  {
    id: "agachamento_livre",
    canonicalNamePt: "Agachamento livre",
    namesByLanguage: {
      "pt-BR": "Agachamento livre",
      "it-IT": "Squat libero",
      "en-US": "Bodyweight squat",
      "es-ES": "Sentadilla libre",
    },
    aliasesByLanguage: {
      "pt-BR": ["agachamento", "squat"],
      "it-IT": ["squat", "squat libero"],
      "en-US": ["squat", "air squat"],
      "es-ES": ["sentadilla", "squat"],
    },
    muscleGroup: "pernas",
    videoUrl: `${V}/pernas-gluteos-panturrilha/agachamanto_livre.mp4`,
    sourceFileName: "agachamanto_livre.mp4",
    videoProvider: "local",
    movementPattern: "agachamento",
    equipment: "bodyweight",
    tags: ["pernas", "gluteos", "corpo-livre"],
  },
  {
    id: "agachamento_isometrico_parede",
    canonicalNamePt: "Agachamento isométrico parede",
    namesByLanguage: {
      "pt-BR": "Agachamento isométrico parede",
      "it-IT": "Squat isometrico a parete",
      "en-US": "Wall sit",
      "es-ES": "Sentadilla isométrica pared",
    },
    aliasesByLanguage: {
      "pt-BR": ["cadeira invisível", "wall sit", "agachamento parede"],
      "it-IT": ["wall sit", "sedia invisibile"],
      "en-US": ["wall sit"],
      "es-ES": ["silla invisible", "wall sit"],
    },
    muscleGroup: "pernas",
    videoUrl: `${V}/pernas-gluteos-panturrilha/agachamento_isometrico_apoio_parede.mp4`,
    sourceFileName: "agachamento_isometrico_apoio_parede.mp4",
    videoProvider: "local",
    movementPattern: "isometrico",
    equipment: "bodyweight",
    tags: ["pernas", "isometrico"],
  },
  {
    id: "agachamento_smith",
    canonicalNamePt: "Agachamento smith",
    namesByLanguage: {
      "pt-BR": "Agachamento smith",
      "it-IT": "Squat al multipower",
      "en-US": "Smith machine squat",
      "es-ES": "Sentadilla en multipower",
    },
    aliasesByLanguage: {
      "pt-BR": ["agachamento smith", "squat smith"],
      "it-IT": ["squat multipower", "squat smith"],
      "en-US": ["smith squat"],
      "es-ES": ["sentadilla smith", "squat smith"],
    },
    muscleGroup: "pernas",
    videoUrl: `${V}/pernas-gluteos-panturrilha/aguachamaneto_smith.mp4`,
    sourceFileName: "aguachamaneto_smith.mp4",
    videoProvider: "local",
    movementPattern: "agachamento",
    equipment: "smith",
    tags: ["pernas", "gluteos"],
  },
  {
    id: "posterior_unilateral_vertical_maquina",
    canonicalNamePt: "Posterior unilateral vertical máquina",
    namesByLanguage: {
      "pt-BR": "Posterior unilateral vertical máquina",
      "it-IT": "Leg curl unilaterale verticale alla macchina",
      "en-US": "Unilateral vertical machine leg curl",
      "es-ES": "Femoral unilateral vertical máquina",
    },
    aliasesByLanguage: {
      "pt-BR": ["leg curl vertical unilateral"],
      "it-IT": ["leg curl verticale"],
      "en-US": ["vertical leg curl unilateral"],
      "es-ES": ["curl femoral vertical"],
    },
    muscleGroup: "pernas",
    videoUrl: `${V}/pernas-gluteos-panturrilha/bosterior_unilateral_vertical_maquina.mp4`,
    sourceFileName: "bosterior_unilateral_vertical_maquina.mp4",
    videoProvider: "local",
    movementPattern: "flexao",
    equipment: "maquina",
    tags: ["pernas", "posteriores"],
  },
  {
    id: "bulgaro_halter",
    canonicalNamePt: "Búlgaro halter",
    namesByLanguage: {
      "pt-BR": "Búlgaro halter",
      "it-IT": "Squat bulgaro con manubri",
      "en-US": "Bulgarian split squat with dumbbells",
      "es-ES": "Sentadilla búlgara mancuernas",
    },
    aliasesByLanguage: {
      "pt-BR": ["búlgaro", "split squat búlgaro"],
      "it-IT": ["bulgaro manubri", "split squat bulgaro"],
      "en-US": ["bulgarian split squat", "bulgarian squat"],
      "es-ES": ["sentadilla búlgara", "búlgaro"],
    },
    muscleGroup: "pernas",
    videoUrl: `${V}/pernas-gluteos-panturrilha/bulgado_halter.mp4`,
    sourceFileName: "bulgado_halter.mp4",
    videoProvider: "local",
    movementPattern: "unilateral",
    equipment: "halter",
    tags: ["pernas", "gluteos"],
  },
  {
    id: "bulgaro_apoio_cadeira",
    canonicalNamePt: "Búlgaro apoio cadeira",
    namesByLanguage: {
      "pt-BR": "Búlgaro apoio cadeira",
      "it-IT": "Squat bulgaro con appoggio alla sedia",
      "en-US": "Bulgarian split squat on chair",
      "es-ES": "Sentadilla búlgara apoyo silla",
    },
    aliasesByLanguage: {
      "pt-BR": ["búlgaro cadeira"],
      "it-IT": ["bulgaro sedia"],
      "en-US": ["chair bulgarian squat"],
      "es-ES": ["búlgaro silla"],
    },
    muscleGroup: "pernas",
    videoUrl: `${V}/pernas-gluteos-panturrilha/bulgaro_apoio_cadeira.mp4`,
    sourceFileName: "bulgaro_apoio_cadeira.mp4",
    videoProvider: "local",
    movementPattern: "unilateral",
    equipment: "bodyweight",
    tags: ["pernas", "gluteos", "corpo-livre"],
  },
  {
    id: "cadeira_abdutora",
    canonicalNamePt: "Cadeira abdutora",
    namesByLanguage: {
      "pt-BR": "Cadeira abdutora",
      "it-IT": "Abduttore alla macchina",
      "en-US": "Hip abduction machine",
      "es-ES": "Máquina abductora",
    },
    aliasesByLanguage: {
      "pt-BR": ["abdutora", "hip abduction"],
      "it-IT": ["abduttore macchina"],
      "en-US": ["hip abduction"],
      "es-ES": ["abductora"],
    },
    muscleGroup: "pernas",
    videoUrl: `${V}/pernas-gluteos-panturrilha/cadeira_abdutora.mp4`,
    sourceFileName: "cadeira_abdutora.mp4",
    videoProvider: "local",
    movementPattern: "abducao",
    equipment: "maquina",
    tags: ["pernas", "gluteos"],
  },
  {
    id: "cadeira_adutora",
    canonicalNamePt: "Cadeira adutora",
    namesByLanguage: {
      "pt-BR": "Cadeira adutora",
      "it-IT": "Adduttore alla macchina",
      "en-US": "Hip adduction machine",
      "es-ES": "Máquina adductora",
    },
    aliasesByLanguage: {
      "pt-BR": ["adutora", "hip adduction"],
      "it-IT": ["adduttore macchina"],
      "en-US": ["hip adduction"],
      "es-ES": ["adductora"],
    },
    muscleGroup: "pernas",
    videoUrl: `${V}/pernas-gluteos-panturrilha/cadeira_adutora.mp4`,
    sourceFileName: "cadeira_adutora.mp4",
    videoProvider: "local",
    movementPattern: "aducao",
    equipment: "maquina",
    tags: ["pernas"],
  },
  {
    id: "cadeira_extensora",
    canonicalNamePt: "Cadeira extensora",
    namesByLanguage: {
      "pt-BR": "Cadeira extensora",
      "it-IT": "Leg extension",
      "en-US": "Leg extension",
      "es-ES": "Extensión de piernas",
    },
    aliasesByLanguage: {
      "pt-BR": ["extensora", "leg extension"],
      "it-IT": ["leg extension"],
      "en-US": ["leg extension"],
      "es-ES": ["extensión piernas"],
    },
    muscleGroup: "pernas",
    videoUrl: `${V}/pernas-gluteos-panturrilha/cadeira_extensora.mp4`,
    sourceFileName: "cadeira_extensora.mp4",
    videoProvider: "local",
    movementPattern: "extensao",
    equipment: "maquina",
    tags: ["pernas", "quadriceps"],
  },
  {
    id: "elevacao_quadril_barra_banco",
    canonicalNamePt: "Elevação de quadril barra banco",
    namesByLanguage: {
      "pt-BR": "Elevação de quadril barra banco",
      "it-IT": "Hip thrust con bilanciere e panca",
      "en-US": "Barbell hip thrust on bench",
      "es-ES": "Hip thrust barra en banco",
    },
    aliasesByLanguage: {
      "pt-BR": ["hip thrust", "elevação quadril barra"],
      "it-IT": ["hip thrust bilanciere"],
      "en-US": ["hip thrust", "barbell hip thrust"],
      "es-ES": ["hip thrust barra"],
    },
    muscleGroup: "pernas",
    videoUrl: `${V}/pernas-gluteos-panturrilha/elevacao_quadril_barra_banco.mp4`,
    sourceFileName: "elevacao_quadril_barra_banco.mp4",
    videoProvider: "local",
    movementPattern: "extensao-quadril",
    equipment: "barra",
    tags: ["gluteos", "pernas"],
  },
  {
    id: "elevacao_quadril_barra_solo",
    canonicalNamePt: "Elevação de quadril barra solo",
    namesByLanguage: {
      "pt-BR": "Elevação de quadril barra solo",
      "it-IT": "Hip thrust con bilanciere a terra",
      "en-US": "Floor barbell hip thrust",
      "es-ES": "Hip thrust barra en suelo",
    },
    aliasesByLanguage: {
      "pt-BR": ["hip thrust solo", "elevação quadril solo"],
      "it-IT": ["hip thrust a terra"],
      "en-US": ["floor hip thrust"],
      "es-ES": ["hip thrust suelo"],
    },
    muscleGroup: "pernas",
    videoUrl: `${V}/pernas-gluteos-panturrilha/elevacao_quadril_barra_solo.mp4`,
    sourceFileName: "elevacao_quadril_barra_solo.mp4",
    videoProvider: "local",
    movementPattern: "extensao-quadril",
    equipment: "barra",
    tags: ["gluteos", "pernas"],
  },
  {
    id: "legpress_45",
    canonicalNamePt: "Leg press 45",
    namesByLanguage: {
      "pt-BR": "Leg press 45",
      "it-IT": "Leg press 45°",
      "en-US": "45° leg press",
      "es-ES": "Prensa de piernas 45",
    },
    aliasesByLanguage: {
      "pt-BR": ["leg press", "prensa pernas"],
      "it-IT": ["leg press"],
      "en-US": ["leg press"],
      "es-ES": ["prensa piernas", "leg press"],
    },
    muscleGroup: "pernas",
    videoUrl: `${V}/pernas-gluteos-panturrilha/legpress_45.mp4`,
    sourceFileName: "legpress_45.mp4",
    videoProvider: "local",
    movementPattern: "empurrar",
    equipment: "maquina",
    tags: ["pernas", "quadriceps", "gluteos"],
  },
  {
    id: "panturrilha_em_pe_maquina",
    canonicalNamePt: "Panturrilha em pé máquina",
    namesByLanguage: {
      "pt-BR": "Panturrilha em pé máquina",
      "it-IT": "Polpaccio in piedi alla macchina",
      "en-US": "Standing calf raise machine",
      "es-ES": "Gemelo de pie máquina",
    },
    aliasesByLanguage: {
      "pt-BR": ["panturrilha em pé", "calf raise em pé"],
      "it-IT": ["polpaccio in piedi"],
      "en-US": ["standing calf raise"],
      "es-ES": ["gemelo de pie"],
    },
    muscleGroup: "pernas",
    videoUrl: `${V}/pernas-gluteos-panturrilha/panturrilha_em_pe_maquina.mp4`,
    sourceFileName: "panturrilha_em_pe_maquina.mp4",
    videoProvider: "local",
    movementPattern: "extensao-plantar",
    equipment: "maquina",
    tags: ["panturrilha"],
  },
  {
    id: "panturrilha_escada",
    canonicalNamePt: "Panturrilha escada",
    namesByLanguage: {
      "pt-BR": "Panturrilha escada",
      "it-IT": "Polpaccio sulle scale",
      "en-US": "Stair calf raise",
      "es-ES": "Gemelo en escalera",
    },
    aliasesByLanguage: {
      "pt-BR": ["panturrilha escada", "calf raise escada"],
      "it-IT": ["polpaccio scala"],
      "en-US": ["stair calf raise"],
      "es-ES": ["gemelo escalera"],
    },
    muscleGroup: "pernas",
    videoUrl: `${V}/pernas-gluteos-panturrilha/panturrilha_escada.mp4`,
    sourceFileName: "panturrilha_escada.mp4",
    videoProvider: "local",
    movementPattern: "extensao-plantar",
    equipment: "escada",
    tags: ["panturrilha"],
  },
  {
    id: "panturrilha_sentado_maquina",
    canonicalNamePt: "Panturrilha sentado máquina",
    namesByLanguage: {
      "pt-BR": "Panturrilha sentado máquina",
      "it-IT": "Polpaccio seduto alla macchina",
      "en-US": "Seated calf raise machine",
      "es-ES": "Gemelo sentado máquina",
    },
    aliasesByLanguage: {
      "pt-BR": ["panturrilha sentado", "calf raise sentado"],
      "it-IT": ["polpaccio seduto"],
      "en-US": ["seated calf raise"],
      "es-ES": ["gemelo sentado"],
    },
    muscleGroup: "pernas",
    videoUrl: `${V}/pernas-gluteos-panturrilha/panturrilha_sentado_maquina.mp4`,
    sourceFileName: "panturrilha_sentado_maquina.mp4",
    videoProvider: "local",
    movementPattern: "extensao-plantar",
    equipment: "maquina",
    tags: ["panturrilha"],
  },
  {
    id: "posterior_deitado_maquina_unilateral",
    canonicalNamePt: "Posterior deitado máquina unilateral",
    namesByLanguage: {
      "pt-BR": "Posterior deitado máquina unilateral",
      "it-IT": "Leg curl prono unilaterale alla macchina",
      "en-US": "Unilateral prone machine leg curl",
      "es-ES": "Femoral tumbado máquina unilateral",
    },
    aliasesByLanguage: {
      "pt-BR": ["leg curl unilateral", "posterior unilateral deitado"],
      "it-IT": ["leg curl unilaterale"],
      "en-US": ["unilateral leg curl"],
      "es-ES": ["curl femoral unilateral"],
    },
    muscleGroup: "pernas",
    videoUrl: `${V}/pernas-gluteos-panturrilha/posterioir_deitado_maquinaunilateral.mp4`,
    sourceFileName: "posterioir_deitado_maquinaunilateral.mp4",
    videoProvider: "local",
    movementPattern: "flexao",
    equipment: "maquina",
    tags: ["pernas", "posteriores"],
  },
  {
    id: "posterior_deitado_maquina",
    canonicalNamePt: "Posterior deitado máquina",
    namesByLanguage: {
      "pt-BR": "Posterior deitado máquina",
      "it-IT": "Leg curl prono alla macchina",
      "en-US": "Prone machine leg curl",
      "es-ES": "Femoral tumbado máquina",
    },
    aliasesByLanguage: {
      "pt-BR": ["leg curl deitado", "posterior deitado"],
      "it-IT": ["leg curl prono"],
      "en-US": ["prone leg curl", "lying leg curl"],
      "es-ES": ["curl femoral tumbado"],
    },
    muscleGroup: "pernas",
    videoUrl: `${V}/pernas-gluteos-panturrilha/posterior_deitado_maquina.mp4`,
    sourceFileName: "posterior_deitado_maquina.mp4",
    videoProvider: "local",
    movementPattern: "flexao",
    equipment: "maquina",
    tags: ["pernas", "posteriores"],
  },
  {
    id: "posterior_maquina",
    canonicalNamePt: "Posterior máquina",
    namesByLanguage: {
      "pt-BR": "Posterior máquina",
      "it-IT": "Leg curl alla macchina",
      "en-US": "Machine leg curl",
      "es-ES": "Femoral en máquina",
    },
    aliasesByLanguage: {
      "pt-BR": ["leg curl", "posterior máquina"],
      "it-IT": ["leg curl macchina"],
      "en-US": ["leg curl"],
      "es-ES": ["curl femoral"],
    },
    muscleGroup: "pernas",
    videoUrl: `${V}/pernas-gluteos-panturrilha/posterior_maquina.mp4`,
    sourceFileName: "posterior_maquina.mp4",
    videoProvider: "local",
    movementPattern: "flexao",
    equipment: "maquina",
    tags: ["pernas", "posteriores"],
  },
  {
    id: "sobe_desce_caixote_unilateral",
    canonicalNamePt: "Sobe desce caixote unilateral",
    namesByLanguage: {
      "pt-BR": "Sobe desce caixote unilateral",
      "it-IT": "Step up unilaterale",
      "en-US": "Unilateral box step-up",
      "es-ES": "Subida caja unilateral",
    },
    aliasesByLanguage: {
      "pt-BR": ["step up", "sobe desce caixote", "box step"],
      "it-IT": ["step up"],
      "en-US": ["step up", "box step-up"],
      "es-ES": ["step up", "subida caja"],
    },
    muscleGroup: "pernas",
    videoUrl: `${V}/pernas-gluteos-panturrilha/sobe_desce_caxote_unilateral.mp4`,
    sourceFileName: "sobe_desce_caxote_unilateral.mp4",
    videoProvider: "local",
    movementPattern: "unilateral",
    equipment: "caixote",
    tags: ["pernas", "gluteos"],
  },
];

// ─── Helpers ───────────────────────────────────────────────────────────────────

const catalogById = new Map<string, CatalogExercise>(
  ValidatedExerciseCatalog.map((e) => [e.id, e])
);

export function getCatalogById(id: string): CatalogExercise | undefined {
  return catalogById.get(id);
}

export function getCatalogByGroup(group: CatalogMuscleGroup): CatalogExercise[] {
  return ValidatedExerciseCatalog.filter((e) => e.muscleGroup === group);
}

export function getExerciseName(id: string, language: CatalogLanguage): string {
  const entry = catalogById.get(id);
  if (!entry) return id;
  return entry.namesByLanguage[language] ?? entry.canonicalNamePt;
}

export function findByAlias(alias: string, language: CatalogLanguage): CatalogExercise | undefined {
  const normalized = alias.toLowerCase().trim();
  return ValidatedExerciseCatalog.find((e) =>
    (e.aliasesByLanguage[language] ?? []).some((a) => a.toLowerCase() === normalized)
  );
}

export function getExercisesForFocus(
  focusKey: string,
  location: "gym" | "home" | "park" = "gym"
): { warmup: string[]; main: string[] } {
  switch (focusKey) {
    case "chest_triceps":
      return {
        warmup: location === "gym" ? ["bike_academia", "escada_academia", "prancha_isometrica"] : ["polichinelo", "perdigueiro", "prancha_isometrica"],
        main: location === "gym"
          ? ["supino_reto", "supino_inclinado_halter", "crucifixo_maquina", "supino_reto_maquina", "triceps_barra_v_cabo", "triceps_frances_cabo", "paralelas_gravitron", "flexao"]
          : ["flexao", "triceps_barra_v_cabo", "paralelas_gravitron"],
      };
    case "back_biceps":
      return {
        warmup: location === "gym" ? ["bike_academia", "escada_academia", "prancha_isometrica"] : ["polichinelo", "perdigueiro", "prancha_isometrica"],
        main: location === "gym"
          ? ["puxada_frente", "remada_baixa_polia", "remada_cavalinho", "remada_neutra_maquina", "biceps_maquina", "rosca_alternada_halter_sentado"]
          // park/home: no dumbbell/machine → bodyweight pulling substitutes
          : ["flexao", "perdigueiro", "prancha_isometrica", "burpee"],
      };
    case "legs_core":
      return {
        warmup: location === "gym" ? ["bike_academia", "prancha_isometrica"] : ["polichinelo", "perdigueiro"],
        main: location === "gym"
          ? ["legpress_45", "cadeira_extensora", "posterior_maquina", "agachamento_livre", "afundo_halter", "prancha_isometrica"]
          // park/home: no dumbbell → agachamento livre + bodyweight conditioning
          : ["agachamento_livre", "prancha_isometrica", "burpee", "perdigueiro"],
      };
    case "shoulders_abs":
      return {
        warmup: location === "gym" ? ["bike_academia", "prancha_isometrica"] : ["polichinelo", "perdigueiro"],
        main: location === "gym"
          ? ["desenvolvimento_sentado", "elevacao_lateral_halter_sentado", "remada_alta_halter", "abs_supra_halter", "prancha_isometrica", "prancha_lateral"]
          // park/home: no dumbbell/machine → bodyweight core/cardio
          : ["flexao", "perdigueiro", "prancha_isometrica", "abs_obliquio", "prancha_lateral"],
      };
    case "full_body":
    default:
      return {
        warmup: ["polichinelo", "perdigueiro"],
        // park/home: no dumbbell → replace serrote with bodyweight perdigueiro
        main: location === "gym"
          ? ["agachamento_livre", "flexao", "serrote", "prancha_isometrica"]
          : ["agachamento_livre", "flexao", "perdigueiro", "prancha_isometrica"],
      };
  }
}
