import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { optimizeNutrition, reoptimizeNutrition, TEST_FIXTURE_ONLY_FOODS, type NutritionTarget } from "../src/v3/nutrition-optimizer/spike/index.js";

const target: NutritionTarget = { calories: { min: 3000, target: 3200, max: 3400 }, proteinGrams: { min: 130, target: 160, max: 190 }, fatGrams: { min: 50, target: 70, max: 100 }, carbsGrams: { min: 250, target: 400, max: 500 }, fiberGrams: { min: 25, max: 80 } };
const snapshot = (result: Awaited<ReturnType<typeof optimizeNutrition>>) => ({ status: result.status, foods: result.foods, totals: result.totals, objectiveValue: result.solverMetadata.objectiveValue });
const valid = (result: Awaited<ReturnType<typeof optimizeNutrition>>) => { assert.equal(result.status, "OPTIMAL"); assert.ok(result.totals.calories >= 3000 && result.totals.calories <= 3400); assert.ok(result.totals.proteinGrams >= 130 && result.totals.proteinGrams <= 190); assert.ok(result.totals.fatGrams >= 50 && result.totals.fatGrams <= 100); assert.ok(result.totals.carbsGrams >= 250 && result.totals.carbsGrams <= 500); assert.ok((result.totals.fiberGrams ?? 0) >= 25); };

describe("HIGHS_JS isolated nutrition optimizer spike", () => {
  it("LP_FEASIBLE", async () => valid(await optimizeNutrition({ target, foods: TEST_FIXTURE_ONLY_FOODS })));
  it("formal absolute-deviation LP and POTATO_REMOVED", async () => { const base = await optimizeNutrition({ target, foods: TEST_FIXTURE_ONLY_FOODS }); valid(base); const next = await reoptimizeNutrition({ previousPlan: base, target, foods: TEST_FIXTURE_ONLY_FOODS, excludedFoodIds: ["potato"] }); valid(next); assert.equal(next.solverMetadata.formulation, "weighted_absolute_deviation_lp"); assert.equal(next.foods.some((f) => f.foodId === "potato"), false); });
  it("RICE_REMOVED safe result", async () => { const base = await optimizeNutrition({ target, foods: TEST_FIXTURE_ONLY_FOODS }); const next = await reoptimizeNutrition({ previousPlan: base, target, foods: TEST_FIXTURE_ONLY_FOODS, excludedFoodIds: ["rice"], roundingGrams: 1 }); assert.ok(["OPTIMAL", "ERROR"].includes(next.status)); assert.equal(next.foods.some((f) => f.foodId === "rice"), false); if (next.status === "ERROR") assert.deepEqual(next.foods, []); });
  it("BANANA_REMOVED safe result", async () => { const base = await optimizeNutrition({ target, foods: TEST_FIXTURE_ONLY_FOODS }); const next = await reoptimizeNutrition({ previousPlan: base, target, foods: TEST_FIXTURE_ONLY_FOODS, excludedFoodIds: ["banana"], roundingGrams: 1 }); assert.ok(["OPTIMAL", "ERROR"].includes(next.status)); assert.equal(next.foods.some((f) => f.foodId === "banana"), false); });
  it("CHICKEN_REMOVED is infeasible or safely rejected", async () => { const base = await optimizeNutrition({ target, foods: TEST_FIXTURE_ONLY_FOODS }); const next = await reoptimizeNutrition({ previousPlan: base, target, foods: TEST_FIXTURE_ONLY_FOODS, excludedFoodIds: ["chicken"] }); assert.ok(["INFEASIBLE", "ERROR", "OPTIMAL"].includes(next.status)); if (next.status !== "OPTIMAL") assert.deepEqual(next.foods, []); });
  it("INFEASIBLE_POOL", async () => { const result = await optimizeNutrition({ target, foods: TEST_FIXTURE_ONLY_FOODS, excludedFoodIds: ["oats", "rice", "potato", "banana"] }); assert.equal(result.status, "INFEASIBLE"); assert.deepEqual(result.foods, []); });
  it("ROLE_POLICY rigid filter and penalty both preserve solver ownership of grams", async () => { const rigid = await optimizeNutrition({ target, foods: TEST_FIXTURE_ONLY_FOODS, roleRequirements: { carb_primary: 1, protein_primary: 1 }, rolePolicy: "rigid_filter" }); valid(rigid); const penalty = await optimizeNutrition({ target, foods: TEST_FIXTURE_ONLY_FOODS, roleRequirements: { carb_primary: 1, protein_primary: 1 }, rolePolicy: "penalty", rolePenalty: { legume: 100 } }); valid(penalty); });
  it("ROUNDING_VALID for 1g, 5g and 10g when feasible", async () => { for (const step of [1, 5, 10]) { const result = await optimizeNutrition({ target, foods: TEST_FIXTURE_ONLY_FOODS, roundingGrams: step }); assert.ok(["OPTIMAL", "ERROR"].includes(result.status)); if (result.status === "OPTIMAL") { valid(result); assert.ok(result.foods.every((f) => f.grams % step === 0)); } else assert.deepEqual(result.foods, []); } });
  it("DETERMINISTIC solver output over 20 runs", async () => { const results = await Promise.all(Array.from({ length: 20 }, () => optimizeNutrition({ target, foods: TEST_FIXTURE_ONLY_FOODS }))); for (const result of results) assert.deepEqual(snapshot(result), snapshot(results[0])); });
  it("TIME_LIMIT_HANDLED without partial plan", async () => { const result = await optimizeNutrition({ target, foods: TEST_FIXTURE_ONLY_FOODS, timeLimitSeconds: 0 }); assert.ok(["TIME_LIMIT", "OPTIMAL", "ERROR"].includes(result.status)); if (result.status !== "OPTIMAL") assert.deepEqual(result.foods, []); });
  it("PERFORMANCE_SMOKE for 7, 25 and 50 candidates", async () => { for (const count of [7, 25, 50]) { const foods = Array.from({ length: count }, (_, i) => ({ ...TEST_FIXTURE_ONLY_FOODS[i % 7], id: `${TEST_FIXTURE_ONLY_FOODS[i % 7].id}_${i}` })); const result = await optimizeNutrition({ target, foods }); assert.ok(["OPTIMAL", "ERROR"].includes(result.status)); assert.ok(result.solverMetadata.durationMs >= 0); } });
});
